# Generated by Django 2.2 on 2019-04-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='channelId',
            field=models.ForeignKey(db_column='channelId', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Channels', to_field='channelId'),
        ),
    ]
