# Generated by Django 2.2 on 2019-04-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190423_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataParserTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('task_items', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_parser_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataParserStatuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, default='idle', max_length=100, null=True)),
                ('status_description', models.TextField(blank=True, default=None, null=True)),
                ('count_items_total', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('count_items_left', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('count_unavailable_videos', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('count_nocaption_videos', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('count_error_videos', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('estimated_quotas_use', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('next_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.DataParserTasks')),
            ],
            options={
                'db_table': 'data_parser_statuses',
                'managed': True,
            },
        ),
    ]
