# Generated by Django 2.2 on 2019-04-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_dataparserstatuses_dataparsertasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='topicCategories',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='topicCategories',
        ),
        migrations.AddField(
            model_name='dataparsertasks',
            name='items_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='commentCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='subscriberCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='videoCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='viewCount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='captionUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
