# Generated by Django 2.2 on 2019-04-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190427_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='channelId',
            field=models.ForeignKey(blank=True, db_column='channelId', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Channels', to_field='channelId'),
        ),
    ]
