# Generated by Django 2.2 on 2019-04-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190428_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataparsertasks',
            name='isFinished',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
