# Generated by Django 2.2 on 2019-04-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_dataparsertasks_isfinished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataparsertasks',
            old_name='task_items',
            new_name='task_item',
        ),
        migrations.RemoveField(
            model_name='dataparsertasks',
            name='items_type',
        ),
    ]
