# Generated by Django 2.2 on 2019-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190428_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataparserstatuses',
            old_name='estimated_quotas_use',
            new_name='quotas_used',
        ),
        migrations.RemoveField(
            model_name='dataparserstatuses',
            name='next_task',
        ),
        migrations.AddField(
            model_name='dataparserstatuses',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dataparserstatuses',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataapiquotas',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataapiquotas',
            name='quotas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dataparsertasks',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='commentCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='dislikeCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='favoriteCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likeCount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='viewCount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
