# Generated by Django 2.2 on 2019-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190428_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataparsertasks',
            name='isFinished',
        ),
        migrations.AddField(
            model_name='dataparsertasks',
            name='finishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
