# Generated by Django 2.2 on 2019-04-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190428_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataparserstatuses',
            old_name='count_items_left',
            new_name='count_items_done',
        ),
        migrations.RenameField(
            model_name='dataparserstatuses',
            old_name='quotas_used',
            new_name='estimated_quotas',
        ),
        migrations.AddField(
            model_name='dataparserstatuses',
            name='fatal_error_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataparserstatuses',
            name='taskId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.DataParserTasks'),
        ),
        migrations.AddField(
            model_name='dataparsertasks',
            name='isFatalError',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
