# Generated by Django 2.2 on 2019-04-28 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190428_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataparserstatuses',
            name='taskId',
            field=models.ForeignKey(blank=True, db_column='taskId', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.DataParserTasks'),
        ),
    ]
