# Generated by Django 2.2 on 2019-04-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190429_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
