# Generated by Django 2.2 on 2019-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190430_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='indexes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='stemmed_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='timeframes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
