# Generated by Django 2.2 on 2019-05-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20190501_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={'managed': True, 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='dataapiquotas',
            options={'managed': True, 'verbose_name_plural': 'Data api quotas'},
        ),
        migrations.AlterModelOptions(
            name='dataparserstatuses',
            options={'managed': True, 'verbose_name_plural': 'Data parser statuses'},
        ),
        migrations.AlterModelOptions(
            name='dataparsertasks',
            options={'managed': True, 'verbose_name_plural': 'Data parser tasks'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'managed': True, 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='videos',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
