# Generated by Django 2.2 on 2019-05-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20190506_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='time',
        ),
    ]
