# Generated by Django 2.2 on 2019-05-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_videos_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
