# Generated by Django 2.2 on 2019-05-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20190506_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
