# Generated by Django 2.2 on 2019-08-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20190506_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataparsertasks',
            name='item_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
