# Generated by Django 2.2 on 2019-08-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_dataparsertasks_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataparserstatuses',
            name='command',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
