# Generated by Django 2.2 on 2019-08-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_dataparserstatuses_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataparserstatuses',
            name='command',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
