# Generated by Django 2.2 on 2019-08-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20190813_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataparserstatuses',
            name='command',
        ),
    ]
