# Generated by Django 2.2 on 2019-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_dataparserstatuses_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='https', max_length=10)),
                ('port', models.PositiveIntegerField()),
                ('ip', models.CharField(max_length=50)),
                ('isAvailable', models.BooleanField(default=True)),
                ('isCaptcha', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
                'db_table': 'proxies',
                'managed': True,
            },
        ),
    ]
