# Generated by Django 2.2 on 2019-11-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_proxies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='indexes',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='stemmed_subtitle',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='timeframes',
        ),
    ]
