# Generated by Django 2.2 on 2019-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20191127_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='lxml_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
