# Generated by Django 2.2 on 2019-12-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_videos_lxml_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxies',
            name='login',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proxies',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
