"""
Django settings for spoketube project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import configparser
from data_parser.data_parser import Connector, YouTubeAPI

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRETS_PATH = os.path.join(BASE_DIR, 'dev', 'secrets')

# If running on dev server then looking for secrets file, otherwise gets values from server environment
if os.path.exists(SECRETS_PATH):
    config = configparser.RawConfigParser()
    config.read(SECRETS_PATH)
    config = config['DEBUG LOCALHOST']
else:
    config = os.environ

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ADMINS = [('Admin', 'admin@example.com')]

ALLOWED_HOSTS = config['ALLOWED_HOSTS'].split(',')

# Application definition

INSTALLED_APPS = [
    'mainapp',
    'mainapp.apps.MyAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'analytical',
    'captcha',
    'storages',
    'compressor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spoketube.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spoketube.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config['RDS_DB_NAME'],
        'USER': config['RDS_USERNAME'],
        'PASSWORD': config['RDS_PASSWORD'],
        'HOST': config['RDS_HOSTNAME'],
        'PORT': config['RDS_PORT'],
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Enable logging on prod server
if not os.path.exists(SECRETS_PATH):
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                'datefmt': "%d/%b/%Y %H:%M:%S"
            },
            'simple': {
                'format': '%(levelname)s %(message)s'
            },
        },
        'handlers': {
            'file': {
                'level': 'DEBUG',
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': '/var/log/app-logs/django.log',
                'when': 'midnight',
                'interval': 1,
                'backupCount': 10,
                'formatter': 'verbose',
            },

        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'DEBUG',
                'propagate': True,
            },
        },
    }


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-EN'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'https://' + config['AWS_CLOUDFRONT_DOMAIN'] + '/'

STATICFILES_STORAGE = 'spoketube.storage.StaticToS3Storage'
COMPRESS_STORAGE = 'spoketube.storage.CachedS3Boto3Storage'

STATICFILES_FINDERS = (
'django.contrib.staticfiles.finders.AppDirectoriesFinder',
'django.contrib.staticfiles.finders.FileSystemFinder',
'compressor.finders.CompressorFinder'
)

EMAIL_BACKEND = 'django_ses.SESBackend'

# Credentials for simple email service
AWS_SES_ACCESS_KEY_ID = config['AWS_SES_ACCESS_KEY_ID']
AWS_SES_SECRET_ACCESS_KEY = config['AWS_SES_SECRET_ACCESS_KEY']
AWS_SES_REGION_NAME = config['AWS_SES_REGION_NAME']
AWS_SES_REGION_ENDPOINT = config['AWS_SES_REGION_ENDPOINT']


# Credentials for storage S3 app
AWS_QUERYSTRING_AUTH = False
AWS_ACCESS_KEY_ID = config['AWS_S3_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = config['AWS_S3_SECRET_ACCESS_KEY']
AWS_STORAGE_BUCKET_NAME = config['AWS_STORAGE_BUCKET_NAME']
AWS_S3_REGION_NAME = config['AWS_S3_REGION']
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'public, max-age=31557600'}
AWS_S3_CUSTOM_DOMAIN = config['AWS_CLOUDFRONT_DOMAIN']
AWS_S3_SECURE_URLS = True
CLOUDFRONT_DOMAIN = config['AWS_CLOUDFRONT_DOMAIN']
CLOUDFRONT_ID = config['AWS_CLOUDFRONT_ID']


# Credentials for compressor
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter',
                        'compressor.filters.cssmin.CSSMinFilter'
                        ]
COMPRESS_PARSER = 'compressor.parser.HtmlParser'
AWS_IS_GZIPPED = True
COMPRESS_URL = STATIC_URL
COMPRESS_OUTPUT_DIR = ''


# Recaptcha and clicky settings
RECAPTCHA_PUBLIC_KEY = config['RECAPTCHA_PUBLIC_KEY']
RECAPTCHA_PRIVATE_KEY = config['RECAPTCHA_PRIVATE_KEY']
CLICKY_SITE_ID = config['CLICKY_SITE_ID']


# Data parser and search module settings
MySQL_conn_admin = Connector(host=config['RDS_HOSTNAME'],
                             port=config['RDS_PORT'],
                             db=config['RDS_DB_NAME'],
                             user=config['RDS_USERNAME'],
                             password=config['RDS_PASSWORD']
                             )

Sphinx_conn_admin = Connector(host=config['SPHINX_HOST'],
                              port=config['SPHINX_PORT'],
                              )

Sphinx_conn_search = Connector(host=config['SPHINX_HOST'],
                               port=config['SPHINX_PORT'],
                               )

YT_DEVELOPER_KEY = config['YT_DEV_KEY']
YT = YouTubeAPI(MySQL_conn_admin, YT_DEVELOPER_KEY)
# YouTube API quotas limit per day
YT_DAY_QUOTAS = int(config['YT_DAY_QUOTAS'])

# Count search results per page (string)
SEARCH_RESULTS_P_PAGE = int(config['SEARCH_RESULTS_P_PAGE'])
# Count speech matches per video on load
SEARCH_MAX_SPEECH_MATCHES = int(config['SEARCH_MAX_SPEECH_MATCHES'])
# Count words on both sides of speech match
SEARCH_SPEECH_AROUND = int(config['SEARCH_SPEECH_AROUND'])
# Count of channels to show in main page statistic
MAIN_COUNT_STATISTIC_CHANNELS = int(config['MAIN_COUNT_STATISTIC_CHANNELS'])

# Charset in sphinx config
ALLOWED_CHARS_EN = [' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a',
             'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
             'u', 'v', 'w', 'x', 'y', 'z', '[', ']', '\'', "\"", '{', '}', ',', ':', '/', '\\', '|', '~',
             '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '=', '+', '.', '<', '>', ';',
             '№', '€'
             ]

# Chars that allowed in subtitles (during parsing)
SPEECH_ALLOWED_CHARS_EN = [' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                          'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a',
                          'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                          'u', 'v', 'w', 'x', 'y', 'z', '[', ']', '\''
                          ]

# Just to keep in mind
SPHINX_NOT_RESERVED_CHARS = ['%', '*', '[', ']', '`', '\'']